    $('.owl-carousel').owlCarousel({
    loop:true,
    margin:0,
    autoplay: true,
    nav:true,
    dots:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        },
        2000:{
            items:1
        }
    }
})
